/**:
  ros__parameters:
    # Lidar settings
    use_lidar: false
    # QoS settings
    input_qos: "SENSOR_DATA"
    # Map clearing settings
    map_clearing_frame_id: "base_footprint" # should be changed to base_link
    # Rviz visualization
    slice_visualization_attachment_frame_id: "base_footprint" # should be changed to base_link 

    static_mapper:
      # esdf_slice_height: 0.0
      # esdf_slice_min_height: -0.1
      # esdf_slice_max_height: 0.3
      esdf_slice_height: 0.09
      esdf_slice_min_height: 0.09
      esdf_slice_max_height: 0.65

    dynamic_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 0.3
